function dlnet = Trainingloop (net, Train_Set, Validation_Set, Test_Set)
if nargin < 1
        net = createLayers();
end
options = trainingOptions("lbfgs", ...
    MaxIterations= 70, ...
    ExecutionEnvironment="cpu", ...
    Plots="training-progress", ...
    ValidationData=Validation_Set, ...
    ValidationFrequency=10, ...
    Verbose=false ...
    );
dlnet = trainnet(Train_Set,net,"crossentropy",options);
classNames = categories(Test_Set{2});
scores = minibatchpredict(dlnet,Test_Set{1});
YTest = scores2label(scores,classNames);
accuracyOfTrainedNet = mean(YTest == Test_Set{2})*100;
disp(accuracyOfTrainedNet)
confusionchart(Test_Set{2},YTest)
end
